#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# The environment's checks, from the environment's networks. `isoloom test` runs it and reads the PASS/FAIL lines.
passed=0; failed=0
pass() { passed=$((passed+1)); echo "isoloom-check: PASS $1"; }
fail() { failed=$((failed+1)); echo "isoloom-check: FAIL $1: $2"; }
# _http URL -> the status code, 000 when nothing answers (curl, else wget, else bash).
_http() {
  if command -v curl >/dev/null 2>&1; then
    c=$(curl -sk -o /dev/null -m 5 -w '%{http_code}' "$1" 2>/dev/null)
  elif command -v wget >/dev/null 2>&1; then
    c=$(wget -q -S -O /dev/null -T 5 --no-check-certificate "$1" 2>&1 | sed -n 's/^ *HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n 1)
  else
    u=${1#*://}; hp=${u%%/*}; p=/${u#*/}; [ "$u" = "$hp" ] && p=/
    h=${hp%%:*}; port=${hp#*:}; [ "$hp" = "$h" ] && port=80
    c=$(H=$h P=$port U=$p timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P && printf "GET %s HTTP/1.0\r\nHost: %s\r\n\r\n" "$U" "$H" >&3 && read -r l <&3 && echo "$l"' 2>/dev/null | sed -n 's/^HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p')
  fi
  echo "${c:-000}"
}
_http_is() { [ "$(_http "$1")" = "$2" ]; }
# _req STATUS|any TEXT CURL-ARGS... -> 0 when the request gets that status (any answer for `any`)
# and its body contains TEXT (if any); $out says why not. Needs curl.
_req() {
  want=$1; text=$2; shift 2
  command -v curl >/dev/null 2>&1 || { out="curl is needed for this check"; return 1; }
  b=$(mktemp); c=$(curl -sk -m 10 -o "$b" -w '%{http_code}' "$@" 2>/dev/null); c=${c:-000}; r=0
  if [ "$want" = any ]; then [ "$c" != 000 ] || r=1; else [ "$c" = "$want" ] || r=1; fi
  if [ $r = 1 ]; then out="expected HTTP $want, got $c"
  elif [ -n "$text" ] && ! grep -qF -- "$text" "$b"; then r=1; out="HTTP $c, but the response doesn't contain the expected text"
  fi
  rm -f "$b"; return $r
}
_http_any() { [ "$(_http "$1")" != 000 ]; }
# _tcp HOST PORT -> 0 when it connects (nc, else bash).
_tcp() {
  if command -v nc >/dev/null 2>&1; then nc -z -w 5 "$1" "$2" >/dev/null 2>&1
  else H=$1 P=$2 timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P' >/dev/null 2>&1
  fi
}
# _exec COMMAND TEXT -> 0 when the command succeeds and its output contains TEXT (if any).
_exec() { out=$(sh -c "$1" 2>&1) && { [ -z "$2" ] || printf '%s\n' "$out" | grep -qF -- "$2"; }; }
# _retry SECONDS COMMAND... -> keeps trying every 2s until it passes or the time is up.
_retry() { _end=$(( $(date +%s) + $1 )); shift; while ! "$@"; do [ "$(date +%s)" -lt "$_end" ] || return 1; sleep 2; done; }

if _retry 600 _http_is 'http://ub1404/' 200; then pass 'web root answers'; else fail 'web root answers' "expected HTTP 200 from http://ub1404/, got $(_http 'http://ub1404/')"; fi

if _retry 30 _tcp 'ub1404' 22; then pass 'ssh answers'; else fail 'ssh answers' "nothing listens at ub1404:22"; fi

if _retry 300 _tcp 'ub1404' 21; then pass 'proftpd answers'; else fail 'proftpd answers' "nothing listens at ub1404:21"; fi

if _retry 30 _tcp 'ub1404' 445; then pass 'samba answers'; else fail 'samba answers' "nothing listens at ub1404:445"; fi

if _retry 30 _tcp 'ub1404' 3306; then pass 'mysql answers'; else fail 'mysql answers' "nothing listens at ub1404:3306"; fi

if _retry 300 _tcp 'ub1404' 6697; then pass 'unrealircd answers'; else fail 'unrealircd answers' "nothing listens at ub1404:6697"; fi

if _retry 600 _tcp 'ub1404' 8080; then pass 'continuum answers'; else fail 'continuum answers' "nothing listens at ub1404:8080"; fi

if _retry 600 _tcp 'ub1404' 3500; then pass 'readme app answers'; else fail 'readme app answers' "nothing listens at ub1404:3500"; fi

if _retry 600 _tcp 'ub1404' 8181; then pass 'sinatra answers'; else fail 'sinatra answers' "nothing listens at ub1404:8181"; fi

echo '== checks/vulnerable-services.sh'
if _retry 0 sh -c 'cd /opt/isoloom && sh checks/vulnerable-services.sh'; then pass 'checks/vulnerable-services.sh'; else fail 'checks/vulnerable-services.sh' "checks/vulnerable-services.sh exited non-zero"; fi

echo "isoloom-check: END $passed passed, $failed failed"
[ "$failed" -eq 0 ]
